name: Deploy

on:
  push:
    branches:
      -  master
  pull_request:
    branches:
      -  master

env:
  CI_SETTINGS__TUSK_VERSION: v0.5.1
  CI_SETTINGS__APP_DOCKER_REPO: airtonix/phaser-tutorial-one_app

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Local bin path
        run: echo "::add-path::~/bin"
      - name: Install tusk
        run: >-
          curl -sL https://git.io/tusk | sh -s --
          -b ~/bin $CI_SETTINGS__TUSK_VERSION
      - name: Build ci image
        run: >-
          tusk ci:docker:build
          --appname=app
          --repo=$CI_SETTINGS__APP_DOCKER_REPO
      - name: Publish image
        run: >-
          tusk ci:docker:publish
          --appname=app
          --tag=$CI_SETTINGS__APP_DOCKER_REPO:builder;
          tusk ci:docker:publish
          --appname=app
          --tag=$CI_SETTINGS__APP_DOCKER_REPO:latest;
          tusk ci:docker:publish
          --appname=app
          --tag=$CI_SETTINGS__APP_DOCKER_REPO:$GITHUB_SHA;
